language: ruby
rvm:
  - 2.2.3
  - 2.3.0
before_install: gem install bundler -v 1.11.2
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
